[MIC-6275] // SwiftGen integration for TinkoffASDKUI module
Tinkoff/AcquiringSdk_IOS pull request #160
Opened 2022-09-05 14:17 UTC by ivanglushko

2022-09-06 10:52 UTC, akhaman requested changes

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringLocalizable.swift
> -    func setup(lang: String? = nil, table name: String? = nil, bundle: Bundle?) {
эти параметры сюда могли передавать через конфигурацию UI модуля. Ты проверил, как это может отразиться на поведение компонента?

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +            let viewTitle = L10n.TinkoffAcquiring.View.Title.payQRCode
Какой-то странный неймспейс `L10`
Мб заменить на что-то более читаемое типа `Localization` или др ?

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> -        )
Вот про это конфигурирование писал выше

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/InputCardRequisites/Utils/PaymentSystemImageResolver.swift
> +    static let mir: UIImage = Asset.CardRequisites.mirLogo.image
картинки изначально были вынесены в приватный экстеншн, чтобы не загромождать код инициализаторами  `UIImage`. Кажется, что сейчас в этом нет необходимости. Давай удалим экстеншн и перенесем картинки прям те места, где они нужны

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/Subviews/PaymentCardRemovableView.swift
> +            .cross.withRenderingMode(.alwaysTemplate),
Вот отсутствие опционалов при резолвинге картинок - кайф)

2022-09-06 10:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/Subviews/PaymentCardRemovableView.swift
> +    static let cross: UIImage = Asset.tuiIcServiceCross24.image
Этот экстеншн тоже можно убрать

2022-09-07 10:39 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +            let viewTitle = L10n.TinkoffAcquiring.View.Title.payQRCode
Это дефолтный неймспес от свифтгена, думаю сделан чтобы как раз таки точно не занимать неймспейс Localization, можем поменять если хочешь на Localization или любой другой

2022-09-07 10:43 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/InputCardRequisites/Utils/PaymentSystemImageResolver.swift
> +    static let mir: UIImage = Asset.CardRequisites.mirLogo.image
done

2022-09-07 14:50 UTC, merged