[MIC-5908] Выпилить лишние workspace и pods
Tinkoff/AcquiringSdk_IOS pull request #172
Opened 2022-09-14 15:31 UTC by ivanglushko

2022-09-15 08:18 UTC, akhaman requested changes

2022-09-15 08:18 UTC, akhaman commented on CHANGELOG.md
> +* [MIC-5908] Выпилить лишние workspace и pods
Давай уж формулировку более корректную напишем)

2022-09-16 14:06 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/API/APIParametersProvider.swift
> +    func additionalParameters(for _: NetworkRequest) -> HTTPParameters {
дурацкое правило конечно)) но почек

2022-09-16 14:13 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/API/APIParametersProvider.swift
> +    func additionalParameters(for _: NetworkRequest) -> HTTPParameters {
а его не будет) это я пару раз прогнал без конфига форматер сори)

2022-09-19 08:20 UTC, akhaman commented on ASDKSample/Podfile
> +project 'ASDKSample.xcodeproj'
Минор. Эту штуку же можно полностью выпилить?

2022-09-19 08:38 UTC, akhaman approved these changes

2022-09-19 09:05 UTC, merged