[MIC-6279] v3 root Payment Controller (use for payment without ui just pure business logic)
Tinkoff/AcquiringSdk_IOS pull request #182
Opened 2022-09-27 12:25 UTC by ivanglushko

2022-09-27 13:27 UTC, akhaman requested changes

2022-09-27 13:27 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
>  }
давай пока что public уберем, чтобы в релиз не попало. Потом отдельно будем тестировать

2022-09-27 13:27 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
>  }
Причем давай везде в новых сущностях уберем public. Пусть лежит в кодовой базе, но пока не используется никем

2022-09-27 13:27 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +//        }
what

2022-09-27 13:27 UTC, akhaman commented on CHANGELOG.md
> +* [MIC-6279] Перенос логики совершения платежей без UI. Из ветки v3/root в текущую v2 версию. PaymentController - позволяет оплачивать (без вью части) только бизнес логика.
ну и это тоже можно убрать, раз пока не public

2022-09-27 13:27 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentFinishRequestData.swift
> +    }
тут же просто маппинг? Почему бы extension в UI модуле просто не сделать?

2022-09-27 13:30 UTC, ivanglushko commented on CHANGELOG.md
> +* [MIC-6279] Перенос логики совершения платежей без UI. Из ветки v3/root в текущую v2 версию. PaymentController - позволяет оплачивать (без вью части) только бизнес логика.
потом затеряется / мы не вспомним про это

2022-09-27 13:30 UTC, ivanglushko commented on README.md
> +* **paymentController** - позволяет совершать оплату (без вью части) только бизнес логика.
тоже потом забуду

2022-09-27 13:52 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +//        }
убрал но не уверен насчет того что там все ок работает, не могу проверить(

2022-09-27 13:53 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentFinishRequestData.swift
> +    }
Ок

2022-09-27 13:57 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentFinishRequestData.swift
> +    }
В итоге оставлю как было ибо ругается на все поля примерно так 'infoEmail' is inaccessible due to 'internal' protection level

2022-09-27 14:00 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/Atomic.swift
> +struct Atomic<Value> {
Поправил

2022-09-27 14:06 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
>  }
убрал где возможно

2022-09-27 14:12 UTC, akhaman commented on CHANGELOG.md
> +* [MIC-6279] Перенос логики совершения платежей без UI. Из ветки v3/root в текущую v2 версию. PaymentController - позволяет оплачивать (без вью части) только бизнес логика.
давай задачку заведем

2022-09-27 14:15 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
> +    // make public in future release
вот задачку завести и тут `// TODO: MIC-xxxx <Bla-bla-bla>`

2022-09-27 14:35 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
> +    // make public in future release
https://jira.tcsbank.ru/browse/MIC-6513

2022-09-27 14:35 UTC, ivanglushko commented on README.md
> +* **paymentController** - позволяет совершать оплату (без вью части) только бизнес логика.
https://jira.tcsbank.ru/browse/MIC-6513

2022-09-27 14:35 UTC, ivanglushko commented on CHANGELOG.md
> +* [MIC-6279] Перенос логики совершения платежей без UI. Из ветки v3/root в текущую v2 версию. PaymentController - позволяет оплачивать (без вью части) только бизнес логика.
https://jira.tcsbank.ru/browse/MIC-6513

2022-09-28 06:16 UTC, akhaman approved these changes

2022-09-28 06:20 UTC, merged