MIC-6582 + MIC-6584 // Добавили возможность менять sdk credentials в Sample App
Tinkoff/AcquiringSdk_IOS pull request #194
Opened 2022-10-11 14:40 UTC by ivanglushko

<img width="200" src="https://user-images.githubusercontent.com/36343782/195121611-dbe2347e-3745-48db-8869-c4bb167f7ef6.png">
<img width="200" src="https://user-images.githubusercontent.com/36343782/195121585-64421376-bd63-4624-8a44-67d8dc7d30c9.png">

2022-10-12 11:14 UTC, ivanglushko commented on ASDKSample/ASDKSample/AppSetting.swift
> +    }
не мое, но уберу

2022-10-12 11:15 UTC, ivanglushko commented on ASDKSample/ASDKSample/UIView+Ext.swift
> +    }
полезно для отрисовки бордеров у вьюх пока верстаешь

2022-10-12 11:15 UTC, ivanglushko commented on ASDKSample/ASDKSample/ViewProtocols.swift
> +typealias ConfigurableAndReusable = Configurable & Reusable
Не вижу тут никакого усложнения просто удобный тайпалиас, Codable = Decodable & Encodable

2022-10-12 11:16 UTC, ivanglushko commented on ASDKSample/ASDKSample/AppSetting.swift
> +    ///
не мое, но уберу

2022-10-12 11:16 UTC, ivanglushko commented on ASDKSample/ASDKSample/CGFloat+Ext.swift
> +    static let eight: CGFloat = 8
по правилу убираем константы в экстеншен, завел данные общие значения чтобы читалось легко + переиспользовалось ибо на макетах отступы обычно 16 и 8

2022-10-12 11:17 UTC, ivanglushko commented on ASDKSample/ASDKSample/AppSetting.swift
> +}
использую в RootViewController

2022-10-12 11:22 UTC, ivanglushko commented on ASDKSample/ASDKSample/CredentialsView.swift
> +}
на МБ такого подхода не было, не знаю насколько удобно, но поправлю

2022-10-12 11:23 UTC, ivanglushko commented on ASDKSample/ASDKSample/VerticalEditableView.swift
> +        }
разницы большой нет, но мне так привычней)

2022-10-12 11:25 UTC, akhaman commented on ASDKSample/ASDKSample/UIView+Ext.swift
> +    }
Лан, давай тока в UISDK это не тащить)

2022-10-12 11:27 UTC, akhaman commented on ASDKSample/ASDKSample/CGFloat+Ext.swift
> +    static let eight: CGFloat = 8
имхо 16 читается лучше sixteen. Эта штука в нескольких файлах используется? Если да, то ок. Тока лучше ренеймнуть во что-то более осмысленное типа `defaultInset`

2022-10-12 11:28 UTC, akhaman commented on ASDKSample/ASDKSample/CredentialsView.swift
> +}
Да и в коре подобный код стайл не везде) Просто все таки open source, лучше придерживаться общих подходов

2022-10-12 11:30 UTC, akhaman commented on ASDKSample/ASDKSample/VerticalEditableView.swift
> +        }
Давай все таки не вводить синтаксический сахар просто ради сахара. Если бы эта штука решала какую-то проблему (как snapkit например), то ок. А так, новому разработчику придется еще немного покопаться в коде, чтобы понять все тонкости и нюансы подобных решений 🙃

2022-10-12 11:51 UTC, akhaman commented on ASDKSample/ASDKSample/RootViewController.swift
> +}
В этой штуке вообще нет необходимости. У тебя настройки не могут поменяться, если находишься на экране BuyProducts

2022-10-13 06:24 UTC, ivanglushko commented on ASDKSample/ASDKSample/AppSetting.swift
> +    private let listKeySdkCredentials = "listKeySdkCredentials"
вынес

2022-10-13 06:24 UTC, ivanglushko commented on ASDKSample/ASDKSample/AppSetting.swift
> +        }
вынес

2022-10-13 06:26 UTC, ivanglushko commented on ASDKSample/ASDKSample/CGFloat+Ext.swift
> +    static let eight: CGFloat = 8
ну чтобы узнать defaultInset нужно в код залезть а .sixteen - сразу читается

2022-10-13 06:39 UTC, ivanglushko commented on ASDKSample/ASDKSample/RootViewController.swift
> +}
как раз таки менялись данные

2022-10-14 13:25 UTC, akhaman requested changes

2022-10-14 13:25 UTC, akhaman commented on ASDKSample/ASDKSample/RootViewController.swift
> +}
Не удалил же

2022-10-18 08:29 UTC, akhaman approved these changes

2022-10-18 08:32 UTC, merged

2022-10-18 09:09 UTC, akhaman commented on ASDKSample/ASDKSample/UIView+Ext.swift
> +extension UIView {
.

2022-10-18 09:09 UTC, akhaman commented on ASDKSample/ASDKSample/UIView+Ext.swift
> +extension UIView {
.