[MIC-6627] PaymentsControllerTests
Tinkoff/AcquiringSdk_IOS pull request #203
Opened 2022-10-21 16:08 UTC by ivanglushko

2022-10-24 09:11 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +
обычно тут пишут `// given`

2022-10-24 09:17 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +        let sutAsProtocol: PaymentProcess
а есть ли смысл sut кастить в протокол? Обычно его как раз такие через явную реализацию проверяют

2022-10-24 09:20 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +    func test_Start_when_paymentFlow_full_InitPayment_success_Charge_success() {
Предлагаю придерживаться более однообразного и читаемого нейминга тест кейсов. Вот хороший пример) 
![image](https://user-images.githubusercontent.com/55531056/197492823-7daf6bad-9c7c-4a9f-8c34-1f22a8f4046a.png)

2022-10-24 17:34 UTC, AnMado13 requested changes

2022-10-24 17:34 UTC, AnMado13 commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/CardPaymentProcessTests.swift
> +        XCTAssertNotNil(didFailedArgs?.error)
Вот причина, почему много таких ассертов плохо:
Если падает один ассерт, то другие даже не проверяются. Теперь представь, что у тебя 15 ассертов. Падает только лишь первый. Ты его правишь и запускаешь тест. Внезапно ты узнаешь, что падает еще и второй. Правишь его. Запускаешь тест по новой... И так далее.
Другое же дело, когда у тебя падают обособленные тесты и ты получаешь информацию обо всех ассертах. Ты идешь и разом все правишь

2022-10-25 09:35 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Core/Protocols/IAcquiringThreeDsService.swift
> +public protocol IAcquiringThreeDsService {
grammar nazi

2022-10-25 09:41 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +            return .failure(GenericError.genericError)
сделал опционалом

2022-10-25 09:44 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/Receipt.swift
> +}
компилятор умеет синтезировать только для структур и енамов ( Ну по крайне мере у меня ругался хотя все чайлды Equatable

2022-10-25 09:45 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/SDK/AcquiringSdk.swift
> -    private let ipAddressProvider: IPAddressProvider
чтобы передать зависимость 
<img width="1118" alt="Screenshot 2022-10-25 at 13 44 53" src="https://user-images.githubusercontent.com/36343782/197741090-8a955b2b-8640-474e-9ef2-eaa516152499.png">

2022-10-25 09:51 UTC, ivanglushko commented on TinkoffASDKUI.podspec
> +	test_spec.source_files = 'TinkoffASDKUI/TinkoffASDKUITests/**/*', 'TinkoffASDKCore/TinkoffASDKCoreTests/Infrastructure/Resources/**/*', 'TinkoffASDKCore/TinkoffASDKCoreTests/Infrastructure/Mocks/**/
убрал все в UI

2022-10-25 09:52 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/OrderOptions.swift
> +}
сейчас проходит не знаю почему)0 
убрал это

2022-10-25 09:53 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +    private var threeDSHandler: IThreeDSWebViewHandler
да из-за cancel

2022-10-25 10:04 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +    private(set) var tdsController: ITDSController
<img width="1042" alt="Screenshot 2022-10-25 at 14 04 26" src="https://user-images.githubusercontent.com/36343782/197745255-efe19a5a-61ea-4c7b-a6a1-9373e46bc530.png">

2022-10-25 10:05 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +
да знаю) для меня главное // when проставить .
Если нужен гивен могу вписать

2022-10-25 10:06 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +        let sutAsProtocol: PaymentProcess
да я так проверяю именно паблик методы, закрытые методы мне не нужны

2022-10-25 10:07 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +    func test_Start_when_paymentFlow_full_InitPayment_success_Charge_success() {
ну прошу тогда помочь мне с неймингом, ибо там все методы закрытые и по ним я ориентируесь в нейминге. Плюс какой флоу начинаю тоже в нейминге прописал

2022-10-25 10:08 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/Resources/UIASDKTestsAssembly.swift
> +    static func makeAcquiringSDK() -> AcquiringSdk {
нет это слова синонимы) можно хоть make / create / assemble / build

2022-10-25 10:16 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/CardPaymentProcessTests.swift
> +        let didFailedArgs = dependencies.paymentDelegateMock.paymentDidFailedPassedArguments
название отображает название функции, могу добавить payment но тут все и так очевидно) нет больше никаких других didFailedArgs

2022-10-25 10:19 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/CardPaymentProcessTests.swift
> +        XCTAssertNotNil(didFailedArgs?.error)
очень душно) 
если тест упадет, я все равно пойду его править до момента пока он не станет зеленым. Плодить 100500 тестов лишь для того чтобы разбить ассерты не вижу смысла. Ведь здесь я проверяю флоу и все нужные параметры для этого флоу. Если разбить тесты то тогда их будет огромное кол-во которые дублируют один и тот же флоу

2022-10-27 13:05 UTC, akhaman requested changes

2022-10-27 13:05 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +    func test_Start_when_paymentFlow_full_InitPayment_success_Charge_success() {
for example:
`func test_start_withFullPaymentFlow_shouldCompleteSuccessfully`

2022-10-28 07:15 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/Constants.swift
> +        static let paymentId = "String"
когда убирал тайалиас задело(

2022-10-28 07:20 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/TestCases/ChargePaymentProcessTests.swift
> +    func test_Start_when_paymentFlow_full_InitPayment_success_Charge_success() {
в нейминге ты пропустил InitPayment & Charge методы - у них могут быть разные состояния. test_start_withFullPaymentFlow_shouldCompleteSuccessfully - не покрывает все косвенные состояния

2022-10-28 07:30 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +            return nil
я не понимаю зачем он нужен, если у нас есть didCancel кложур

2022-10-28 09:59 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/ChargePaymentProcess.swift
> +        let request = paymentsService.charge(data: newData) { [weak self] result in
поправил

2022-10-28 10:00 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUITests/Infrastructure/Resources/UIASDKTestsAssembly.swift
> +    }
удалил/ раньше нужен был когда не все протоколы написал для тестов

2022-10-28 12:42 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    public var onUserTapCloseButton: (() -> Void)?
это кложура не вызывается. удоли

2022-10-28 12:42 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    case success(payload: Payload)
корректнее `finished` будет

2022-10-28 12:47 UTC, akhaman requested changes

2022-10-28 12:47 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +public final class ThreeDSWebViewHandler<Payload: Decodable>: IThreeDSWebViewHandler {
internal

2022-10-28 12:47 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    public enum ThreeDSError: Swift.Error {
internal/private

2022-10-28 12:47 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/ChargePaymentProcess.swift
>          }
у тебя уже оно должно использоваться как String, кастинг в Int64 не нужен

2022-10-28 12:47 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/ChargePaymentProcess.swift
> +                rebillId: String(parentPaymentId)
чуть выше убери кастинг, и тут не нужно будет кастить

2022-10-28 12:47 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/ChargePaymentProcess.swift
> +                rebillId: String(parentPaymentId)
кастинг не нужен

2022-10-28 15:25 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    public var onUserTapCloseButton: (() -> Void)?
требование протокола

2022-10-28 15:25 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +public final class ThreeDSWebViewHandler<Payload: Decodable>: IThreeDSWebViewHandler {
паблик ибо торчит в сдк

2022-10-28 15:44 UTC, ivanglushko commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    case success(payload: Payload)
поправил

2022-10-29 13:18 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +    public var onUserTapCloseButton: (() -> Void)?
Так ты же этот протокол написал. Удали там тоже

2022-10-29 13:19 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/3DS/WebViewHandler/ThreeDSWebViewHandler.swift
> +public final class ThreeDSWebViewHandler<Payload: Decodable>: IThreeDSWebViewHandler {
Замени там возвращаемый результат на `IThreeDSWebViewHandler`

2022-11-01 06:40 UTC, merged