[MIC-6821] Added Snackbar for presenting snacks
Tinkoff/AcquiringSdk_IOS pull request #221
Opened 2022-11-21 12:04 UTC by ivanglushko

2022-12-12 13:38 UTC, akhaman requested changes

2022-12-13 06:52 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UIApplication+Ext.swift
> +}
удалил более не нужен

2022-12-13 06:53 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Views/Snackbar/SnackbarViewController.swift
> +        viewController.viewDidLoad()
удалил assemble код

2022-12-13 06:54 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Views/Snackbar/SnackBarPresentable.swift
> +}
Сейчас, не планируется, но я предлагаю оставить (для дебага и для будущ). Если очень режет что такой функционал есть, могу удалить.

2022-12-13 07:41 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Views/Snackbar/SnackBarPresentable.swift
> +}
удалил

2022-12-13 10:50 UTC, akhaman approved these changes

2022-12-13 10:51 UTC, merged