* [MIC-6824] [MIC-6843] [MIC-6837] [MIC-6841] Redesigned Card List Screen
Tinkoff/AcquiringSdk_IOS pull request #239
Opened 2022-12-19 10:18 UTC by ivanglushko

2022-12-20 20:15 UTC, akhaman requested changes

2022-12-20 20:15 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/CardField/CardFieldMaskingFactory.swift
> +    private var listenerStorage: [NSObject] = []
вот этот момент обсуждали голосом на той неделе. Фабрика не должна хранить в себе подобное состояние. 

buildForCardNumber и прочие методы, которые по своей природе должны просто что-то создать и вернуть, фактически изменяют состояния самой фабрики.

2022-12-20 20:15 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/CardField/CardFieldMaskingFactory.swift
> +        listener.didFill = { [weak self] text, completed, textField in
вот здесь корректность работы всей этой системы зависит от того, очистилась фабрика из памяти или нет. 
Не гуд. Ты можешь сильно захватить inputMaskResolver - это решит проблему. 
```swift
listener.didFill = { [inputMaskResolver] text, completed, textField in 
```

2022-12-20 20:15 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/CardField/CardFieldMaskingFactory.swift
> +    private var listenerStorage: [NSObject] = []
а если фабрика выгрузится из памяти, то пропадут ссылки на слушателей. Насколько понял это приведет к некорректной работе. Я бы предложил подумать над иным решением этой архитектурной задачки)

2022-12-20 20:17 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/Global.swift
> +func performOnMain(_ closure: @escaping @convention(block) () -> Void) {
а еще чот хз, не оч нравится, когда что-то лежит в глобальном скоупе. Чисто интуитивно проще, когда оно располагается там, где должно. Этой шутке место, на мой взгляд, в extension DispatchQueue

2022-12-22 09:33 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift
> +    // MARK: - For testing only funcs
не это чтобы я мог заинжектить нужные данные для написания тестов. 
тут не для дебага (возможно уйдут костыли после переделки мвп методов (чтобы не ломал однонаправленность)

2022-12-22 09:35 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift
> +            performOnMain { [weak self] in
зачастую мы ходим в сеть и именно эти запросы я пытаюсь обезопасить. Или ты предлгаешь делать обертки поверх нетворк сервисов?

2022-12-22 09:35 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift
> +        let mode = StubMode.serverError { [weak self] in self?.didTapServerErrorStubButton() }
поправлю

2022-12-22 09:36 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListView.swift
> +        layout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
да помогло, без него не работал аутолейаут(

2022-12-22 09:36 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListView.swift
> +    init(style: Style, delegate: CardListViewDelegate? = nil, stubBuilder: IStubViewBuilder) {
поправлю

2022-12-22 09:37 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListView.swift
> +            return prepareCardCell(cardModel: cardModel!, indexPath: indexPath)
соглы поправлю

2022-12-22 09:37 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListView.swift
> +    private var addCardButtonModel: Any?
это удалю, осталось как артефакт старого тест кода)

2022-12-22 09:37 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListView.swift
> +            self.collectionView(collectionView, didSelectItemAt: indexPath)
хайлайт не нужен

2022-12-22 09:38 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListViewController.swift
>      private weak var externalAlertsFactory: AcquiringAlertViewProtocol?
++ удалю

2022-12-22 09:38 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListViewController.swift
> +        cardListView = CardListView(style: style, stubBuilder: stubBuilder)
окей

2022-12-22 09:39 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/CardListViewController.swift
> +                presenter?.viewNativeAlertDidTapButton()
да, наверное излишние, думал мб понадобиться че потом аналитить

2022-12-22 09:40 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/Subviews/PaymentCardRemovableView.swift
> +    private func setupViews() {
ахахах я и стек несовместимо, ну некст тайм мб попробую на стеках

2022-12-22 09:41 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/Subviews/PaymentCardRemovableView.swift
> +extension PaymentCardRemovableView: ConfigurableItem, Configurable {
вообще легаси Configurable норм но он не хранит configuration внутри, брал реализацию из вью компонентов коры и они хранят configuration для вью, это иногда очень выручает для динамики и тд

2022-12-22 09:42 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/View/Subviews/PaymentCardRemovableView.swift
>  }
да согласен, поправлю

2022-12-22 09:45 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Abstractions/Editable.swift
> +protocol Editable {
Сейчас только TextField реализует Editable абстракции, и 2 компонента Activatable. Использую по аналогии как туи, чтобы просто были доступны данные проперти.

2022-12-22 09:46 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/CardField/CardFieldView + Config.swift
> +    struct Data {}
уберу

2022-12-22 09:47 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/CardField/CardFieldView.swift
> +    private func apply(data: Data) {}
уберу

2022-12-22 09:49 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/TextField/TextField.swift
> +}
использую внутри  **weak var updater: ITextFieldUpdater?**

2022-12-22 09:49 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/TextField/TextField.swift
> +        )
я просто пробрасываю наверх евенты, такая же реализация в туи

2022-12-22 10:28 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift
> +    // MARK: - For testing only funcs
Понял. В целом, если класс не тестируется без доп функций, значит написан не правильно

2022-12-22 10:29 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift
> +            performOnMain { [weak self] in
в этом классе только провайдер ходит в сеть. И то он уже работает возвращает все из главного потока (под капотом у него CardListDataProvider).

2022-12-29 13:07 UTC, akhaman requested changes

2022-12-29 13:46 UTC, merged