[MIC-4762] Add YandexPayButton integration
Tinkoff/AcquiringSdk_IOS pull request #241
Opened 2022-12-21 07:42 UTC by akhaman

- Релализовал шторку для показа процесса загрузки (PaymentActivityView)
- Доработал Core, UI модули перед интеграцией кнопки
- Добавил интерфейсы для кнопки в UI модуль
- Добавил отдельный модуль `TinkoffASDKYandexPay` с реализацией интерфейсов
- Добавил кнопку в Sample
- Поправил тесты после рефакторинга

P.S автотесты на новый функционал не написаны. Будут в след ПР

2022-12-22 09:22 UTC, ivanglushko requested changes

2022-12-22 09:22 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/YandexPay/Models/YandexPayPaymentResult.swift
> +    public struct PaymentInfo {
я бы типы ниже спустил, чтобы в енаме сразу видно было кейсы

2022-12-22 09:22 UTC, ivanglushko commented on TinkoffASDKYandexPay/TinkoffASDKYandexPay/Domain/YandexPayButtonContainerController/YandexPayButtonContainerController.swift
> +private extension DispatchQueue {
вынести?

2022-12-22 09:33 UTC, akhaman commented on ASDKSample/ASDKSample/ContainerTableViewCell.swift
> +        cellContentView = nil
здесь предполагается, что контент задается в методе `cellForRowAt`
Если не удалять контент, появляется вероятность, что одна и та же вьюха будет установлена 2 раза -> runtime crash

2022-12-22 09:34 UTC, akhaman commented on ASDKSample/ASDKSample/YPButtonContainerView.swift
> +final class YPButtonContainerView: UIView {
это все xcodeproj))
<img width="293" alt="image" src="https://user-images.githubusercontent.com/55531056/209104153-20ba3c10-f7e8-4028-a65a-0982f9a170be.png">

поправлю

2022-12-22 09:35 UTC, akhaman commented on ASDKSample/Podfile
> +install! 'cocoapods', share_schemes_for_development_pods: true, preserve_pod_file_structure: true
таргеты девелопмент подов будут добавляться в схемы
<img width="239" alt="image" src="https://user-images.githubusercontent.com/55531056/209104337-3da1e23e-a479-47f0-a997-5921172af636.png">

Так удобнее билдить/запускать тесты отдельного таргета

2022-12-22 09:37 UTC, akhaman commented on ASDKSample/Podfile
> +  pod 'TinkoffASDKYandexPay', :path => '../'
выглядело норм. Чекнул - там где то tab используется, где-то пробелы. Поправлю
<img width="503" alt="image" src="https://user-images.githubusercontent.com/55531056/209104693-fa9d7916-833b-4b9d-829e-1b25f84c1b57.png">

2022-12-22 09:40 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Core/Utils/Extensions/Optional+Utils.swift
> +    /// Более удобный аналог оператора `??` для цепочек вызовов функций
удобнее цепочные вызовы функций обрабатывать:

```swift
try container
            .decodeIfPresent([SafeDecodable<TerminalPayMethod>].self, forKey: .payMethods)
            .or([])
            .compactMap(\.decodedValue)
```

Вместо

```swift
try (container.decodeIfPresent([SafeDecodable<TerminalPayMethod>].self, forKey: .payMethods) ?? [])
            .compactMap(\.decodedValue)
```

2022-12-22 09:43 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/TerminalInfo/TerminalPayMethods/TerminalPayMethod.swift
> +        let methodType = try container.decode(MethodType.self, forKey: .payMethod)
`TerminalPayMethod` может падать - это ок.

Безопасность для расширения api реализована на уровень выше, когда парсим массив из `TerminalPayMethod `

<img width="787" alt="image" src="https://user-images.githubusercontent.com/55531056/209105784-df5961e7-f081-4ac2-bba6-5945594a4ede.png">

2022-12-22 09:46 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/TerminalInfo/TerminalPayMethods/YandexPayMethod.swift
> +    public let showcaseId: String
Да. Если не придут, то мы тупо не сможем юзать YP, посколько все они нужны для инициализации либо `YandexPaySKDApi`, либо для `YandexPayButton`. В такой ситуации проще упасть на запросе, нежели обрабатывать опционалы в бизнес-слое, а там нам все равно придется выбросить ошибку.

2022-12-22 09:46 UTC, akhaman commented on TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Requests/Implementations/GetTerminalPayMethodsRequest.swift
> +struct GetTerminalPayMethods: AcquiringRequest {
пасиба, поправлю

2022-12-22 09:47 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/DispatchQueue+Utils.swift
> +        if Thread.isMainThread {
в текущей ветке ее нет. Предлагаю юзать скоуп `DispatchQueue` тк интуитивно понятнее что где лежит

2022-12-22 09:48 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/PaymentActivity/ViewController/PaymentActivityViewController.swift
> +    private func setupView() {}
Нет. Удалю

2022-12-22 09:48 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/YandexPayPaymentProcess.swift
> +    static let threeDSCompInd = "N"
да

2022-12-22 09:50 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/YandexPayPaymentProcess.swift
> +    static let threeDSCompInd = "N"
в случае с YP мы не делаем запрос `check3DSVersion` -> не можем динамически получить версию -> Юзаем хардкод. Мне тоже не нравится, но Настя сказала, что пока другого варианта нет

2022-12-22 09:52 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/YandexPay/Models/YandexPayPaymentResult.swift
> +    public struct PaymentInfo {
ХЗ. Предпочитаю, когда все соответсвует общепринятым код стайлам (по возможности)

Для меня ориентир - Alamofire (типы наверху, потом кейсы/свойства, потом init, потом функции)
https://github.com/Alamofire/Alamofire/blob/master/Source/AFError.swift

2022-12-22 09:53 UTC, akhaman commented on TinkoffASDKYandexPay/TinkoffASDKYandexPay/Domain/YandexPayButtonContainerController/YandexPayButtonContainerController.swift
> +private extension DispatchQueue {
Ну в этом модуле этот экстеншен только в 1 файле нужен. Обычно выношу, когда переиспользовать в других местах надо. Могу вынести, не принципиально

2022-12-22 09:54 UTC, akhaman commented on ASDKSample/ASDKSample/AppDelegate.swift
> +import YandexPaySDK
пасиба, поправлю

2022-12-22 09:55 UTC, akhaman commented on ASDKSample/ASDKSample/BuyProductsViewController.swift
> +    private var rebuidIdCards: [PaymentCard]?
это я не трогал, так было) 
Правильно будет `rebill`
ПОправлю

2022-12-22 10:15 UTC, ivanglushko commented on ASDKSample/ASDKSample/ContainerTableViewCell.swift
> +        cellContentView = nil
Тогда теряется смысл реюза если мы каждый раз будем создавать вьюху

2022-12-22 10:15 UTC, akhaman commented on ASDKSample/ASDKSample/YPButtonContainerView.swift
> +final class YPButtonContainerView: UIView {
А у нас в целом в сэмпле не предусмотрена иерархия. Править это - попахивает отдельной задачкой. Го потом

<img width="363" alt="image" src="https://user-images.githubusercontent.com/55531056/209111903-e42222fd-1cb6-4d51-9e11-dd0afb0f5c5b.png">

2022-12-22 10:16 UTC, ivanglushko commented on ASDKSample/ASDKSample/YPButtonContainerView.swift
> +final class YPButtonContainerView: UIView {
ааа вот почему не видно путь нормально

2022-12-22 10:53 UTC, ivanglushko approved these changes

2022-12-23 18:17 UTC, ivanglushko approved these changes

2022-12-27 14:27 UTC, merged