[MIC-6833] [MIC-6834] [MIC-6835] [MIC-6836] - Add New Card Screen Redisign
Tinkoff/AcquiringSdk_IOS pull request #246
Opened 2022-12-27 13:43 UTC by ivanglushko

2023-01-09 17:32 UTC, akhaman requested changes

2023-01-10 07:32 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardViewController.swift
> +}
Учесть, что при Свайпе тоже cancelled

2023-01-10 07:34 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardViewController.swift
> +}
во флоу с модальным экраном и с navigation controller

2023-01-10 07:45 UTC, akhaman commented
Обсудили голосом. Стоит переделать CardFieldView:
- избавиться от костыльного взаимодействия с клиентским кодом через замыкания, пробрасываемые через несколько классов
- сделать его обособленным (чтобы можно было взять и переиспользовать его на других экранах, не реализуя такое же взаимодействие через вьюхи и презентеры)
- СardFieldPresenter не должен ничего знать про CardFieldView, он просто получает события/данные

2023-01-11 06:55 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Colors/ASDKColors.swift
> +                dark: UIColor.white.withAlphaComponent(0.3)
<img width="586" alt="Screenshot 2023-01-11 at 10 50 35" src="https://user-images.githubusercontent.com/36343782/211737387-8dab03fb-452a-4070-8a1d-f69621d73649.png">

Можно конечно и hex указать но в дизайнах вроде альфа важна (приложил сурс)

2023-01-11 07:16 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Colors/ASDKColors.swift
> +                dark: UIColor.white.withAlphaComponent(0.3)
Пошел уточнять у дизайнера

2023-01-11 07:48 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardView.swift
> +        }
У меня получается так что ячейка не занимает всю доступную ширину экрана, так как ее лейаут основывается на контенте. А контент занимает минимальную нужную ширину для отрисовки.

2023-01-11 07:51 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +        if case AcquiringUiSdkError.userCancelledCardAdding = error {
Это сделано с целью подружить старый AcquiringCardListDataSourceDelegate и новую реализацию, возможно, не так понял. Но вроде как если там получим nil значит добавление карты отменилось?
А так сейчас по новой логике на дисмисс / или поп происходит отправка события .cancelled в аутпут клиенту.

<img width="928" alt="Screenshot 2023-01-11 at 11 49 21" src="https://user-images.githubusercontent.com/36343782/211748033-a3cc0479-34a0-4106-a2a4-3215570c6e42.png">

2023-01-11 07:55 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardView.swift
> +}
Не знаю насколько они глобальные, пока добавил чисто для реализации AddNewCardView

2023-01-11 07:56 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/PopupViewController(new)/PopupViewController.swift
> +
не используем

2023-01-11 07:56 UTC, ivanglushko commented on Utils/KeyboardService.swift
> +final class KeyboardService {
Спасибо. Удалил

2023-01-11 08:52 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Colors/ASDKColors.swift
> +                dark: UIColor.white.withAlphaComponent(0.3)
<img width="395" alt="Screenshot 2023-01-11 at 12 52 09" src="https://user-images.githubusercontent.com/36343782/211760957-23622db5-34ea-4058-b2e6-214d83bf1222.png">

2023-01-11 11:07 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/DispatchQueue+Ext.swift
> +    /// Исполняет код на Main потоке, если текущий тред не Main
поправил

2023-01-12 11:46 UTC, akhaman commented on ASDKSample/ASDKSample/RootViewController.swift
> +            break
давай Алерт здесь выведем, иначе при ручном тестировании не получится это проверить

2023-01-12 11:55 UTC, ivanglushko commented on ASDKSample/ASDKSample/RootViewController.swift
> +            break
давай

2023-01-12 11:57 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
тут похожая на предыдущую ситуация. IAddNewCardPresenter - абстракция, которая ничего не знает о своей конкретной реализации.  CardFieldPresenter.ValidationResult - указывает на конкретную реализацию

2023-01-12 11:58 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
давай VaidationResult переименуем и вынесем из скоупа презентера

2023-01-12 12:01 UTC, ivanglushko commented on ASDKSample/ASDKSample/RootViewController.swift
> +            break
добавил

2023-01-12 12:03 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
Тут скорее я брал неймспейс от презентера

2023-01-12 12:04 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
имеешь ввиду что если надо будет делать протокол публичным, тогда такой неймпейс сломается и надо делать отдельный тип (не вложенный) ?

2023-01-12 12:21 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
поправил

2023-01-12 12:22 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
ну у тебя протокол ничего не должен знать о своей реализации, иначе смысла в этом протоколе мало

2023-01-12 12:23 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
вряд ли он публичным будет

2023-01-12 12:25 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
А как он знает о реализации ? если CardFieldPresenter.ValidationResult это просто путь до нужной модели

2023-01-12 12:39 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +        if case AcquiringUiSdkError.userCancelledCardAdding = error {
В старой логике `nil` - отмена добавления. В идеале это событие происходит при закрытии экрана 3DS, но учитывая кол-во багов в CardListDataProvider, может  и в ином кейсе выстрелить. В кард листе мы потом тоже заменим тип возвращаемого результата. Пока достаточно, чтобы ты в этом месте (на скрине) определял nil как .cancelled, а не .failure

2023-01-12 13:36 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +    func cardFieldValidationResultDidChange(result: CardFieldPresenter.ValidationResult)
Ну у тебя CardFieldPresenter - это реализация

2023-01-12 14:05 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Modules/AddNewCard/AddNewCardPresenter.swift
> +        if case AcquiringUiSdkError.userCancelledCardAdding = error {
Спасибо так стало понятнее, тогда буду возвращать cancelled

2023-01-13 10:05 UTC, akhaman approved these changes

2023-01-16 06:51 UTC, merged