[MIC-7380] SBP Redesign
Tinkoff/AcquiringSdk_IOS pull request #254
Opened 2023-01-11 19:08 UTC by PravosudovTinkoff

2023-01-12 09:51 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Abstractions/Identifiable.swift
> +protocol Identifiable {
Вроде не юзается?

2023-01-12 09:51 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/UIComponents/Views/Stub/StubViewPresentable.swift
> +        objc_setAssociatedObject(self, &kStubViewManagerAssociatedKey, manager, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
Найс хак)

2023-01-12 10:03 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
> +//            )
актуально?

2023-01-12 10:05 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
UILabel можно сконфигурировать через UILabel.configure(_ configuration:) Есть уже заготовленные стили в разделе UILabel.Style

2023-01-12 10:05 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
> +//            )
ну потом конечно удалю, пока не зафиналим SBP оставлю

2023-01-12 10:06 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UITableView+Ext.swift
> +        register(cellType, forCellReuseIdentifier: cellType.identifier)
ReusableIdentifier думаю будем убирать, не удобно

2023-01-12 10:07 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +     Примечание. Безопасно вызывать только из  main треда.
Я бы наверх поднял чтобы сначала прочесть суть функции, потом уже параметры

2023-01-12 10:09 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
покажи подходящий если он есть, я не нашел

2023-01-12 10:11 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Common/Models/Module.swift
> +    let view: UIViewController
Нужен ли вью? 
Вроде как здесь Input & Output должны присутствовать

2023-01-12 10:13 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +    private static var workItems = [AnyHashable: DispatchWorkItem]()
А почему тут решил по другому поступить (вместо objc_setAssociatedObject как использовал выше) ?

2023-01-12 10:13 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +    private static var workItems = [AnyHashable: DispatchWorkItem]()
просто интересно)

2023-01-12 10:13 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Common/Models/Module.swift
> +    let view: UIViewController
Появится кейс с оутпутом, допишем, пока не надо было

2023-01-12 10:14 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +     Примечание. Безопасно вызывать только из  main треда.
Исправил

2023-01-12 10:16 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
<img width="1069" alt="Screenshot 2023-01-12 at 14 16 09" src="https://user-images.githubusercontent.com/36343782/212040206-6bcf5ede-25d7-4151-a512-c752609e772a.png">

2023-01-12 10:17 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
можешь добавлять нужные проперти в Style и делать новые set функции (думаю что в будущем через KeyPath можно сделать будет решение)
Я у себя сейчас как раз добавил lineBreakMode и по дефолту поставил clipping
<img width="746" alt="Screenshot 2023-01-12 at 14 17 24" src="https://user-images.githubusercontent.com/36343782/212040506-d19dfe98-de32-4832-ae6c-88ac72845abc.png">

2023-01-12 10:18 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
<img width="724" alt="Screenshot 2023-01-12 at 14 18 08" src="https://user-images.githubusercontent.com/36343782/212040666-fe69ff33-844d-43f0-9a94-4c1719f4ccc4.png">

2023-01-12 10:18 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +    private static var workItems = [AnyHashable: DispatchWorkItem]()
всмысле?) там свойство объекта, тут статичное

2023-01-12 10:22 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UITableView+Ext.swift
> +        register(cellType, forCellReuseIdentifier: cellType.identifier)
Если не сложно попробуй тогда убрать его и оставить identifier only

2023-01-12 10:26 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Common/Extensions/DispatchQueue+Ext.swift
> +    private static var workItems = [AnyHashable: DispatchWorkItem]()
так видимо я понял почему (неактуально более)

2023-01-12 10:27 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
не знаю)) количество кода не уменьшается, очевидность и простота уходит, какой смысл?

2023-01-12 10:29 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UITableView+Ext.swift
> +        register(cellType, forCellReuseIdentifier: cellType.identifier)
как я его уберу, это отдельная задачка уже какая то, на рефактор

2023-01-12 11:05 UTC, akhaman requested changes

2023-01-12 11:23 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Resources/Strings/en.lproj/Localizable.strings
> +"CommonAlert.SBPNoBank.Title" = "I couldn't find the application of this bank";
<img width="921" alt="Снимок экрана 2023-01-12 в 15 23 46" src="https://user-images.githubusercontent.com/121286476/212054425-753c403d-fb20-4a60-8c63-d9166faa6ee8.png">

2023-01-12 11:26 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UITableView+Ext.swift
> +    func register<T: UITableViewCell>(cellType: T.Type) {
да, нормас, исправил

2023-01-12 11:35 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Aseembly/SBPBanksAssembly.swift
> +}
не совсем согласен что это прям под все кейсы попадает про модификаторы доступа (например в презентуете может быть некий приватный enum с некими стендами экрана и тд, его бы очень хотелось увидеть сразу сверху), но все константы точно стоит уносить вниз, что б не мешались сверху, сейчас все перенесу

2023-01-12 11:37 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/Resources/Strings/en.lproj/Localizable.strings
> +"CommonAlert.SBPNoBank.Title" = "I couldn't find the application of this bank";
Окей, на всякий случай уточнил)

2023-01-12 11:40 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Aseembly/SBPBanksAssembly.swift
> +}
Вынес все что нашел (в трех файлах), мб что то пропустил, но если в будущем найду унесу вниз

2023-01-12 11:40 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Aseembly/SBPBanksAssembly.swift
> +}
Если этот энум приватный, то он вполне может располагаться в скоупе презентера (наверху). В таком случае и принцип упорядочивания не нарушается, и видно его будет сразу)

2023-01-12 11:42 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Presenter/SBPBanksPresenter.swift
> +final class SBPBanksPresenter: ISBPBanksPresenter, ISBPBanksModuleInput {
ну тут такая тема, я просто считаю их базовыми протоколами, которые надо видеть сразу когда смотришь на класс, а все методы относящиеся к ним находятся под соотвествующими марками. Ну это можно вынести на обсуждение

2023-01-12 11:46 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Presenter/SBPBanksPresenter.swift
> +        DispatchQueue.main.asyncDeduped(target: self, after: 0.3) { [weak self] in
ну по сути это одно и тоже, я как раз хотел уйти от таймер для этой задачи)
сейчас точно переделывать на таймер не буду, но можно обсудить, если не нравится, закинем задачку в бэклог на переделку

2023-01-12 12:06 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Services/SBPBanksService/SBPBanksServiceNew.swift
> +        })
ага, прикольно, сделал еще короче

2023-01-12 12:07 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/Extensions/UITableView+Ext.swift
> +        register(cellType, forCellReuseIdentifier: cellType.identifier)
можно отдельной задачей (не вижу криминала тут исправить там не так много править)

2023-01-12 12:08 UTC, ivanglushko commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Cell/SBPBankCellNew.swift
> +        nameLabel.textColor = ASDKColors.Text.primary.color
Можно формировать стайл и передавать его, а так сейчас лейбл напрямую модифицируешь

2023-01-12 12:19 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/Cells/SBPBankCell/Presenter/ISBPBankCellNewPresenter.swift
> +    var action: EmptyBlock { get }
возможно ты прав, мне не принципиально, переименовал)

2023-01-12 12:20 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Services/SBPBanksService/ISBPBanksService.swift
> +typealias SBPBanksServiceLoadBanksCompletion = (Result<[SBPBank], Error>) -> Void
ничего не решает, чисто привычка и вкусовщина, привык что все кложуры должны быть названы)

2023-01-12 12:22 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Views/SBPBanksViewController.swift
> +    private func setupSerachController() {
весело)) поправил

2023-01-12 12:28 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Presenter/SBPBanksPresenter.swift
> +final class SBPBanksPresenter: ISBPBanksPresenter, ISBPBanksModuleInput {
Повторюсь: минор, оставляй на свое усмотрение)

2023-01-12 12:30 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Presenter/SBPBanksPresenter.swift
> +        DispatchQueue.main.asyncDeduped(target: self, after: 0.3) { [weak self] in
без проблем, можем так оставить. Главное - указал, что этот метод только для главного потока

2023-01-12 12:41 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Services/SBPBanksService/ISBPBanksService.swift
> +typealias SBPBanksServiceLoadBanksCompletion = (Result<[SBPBank], Error>) -> Void
ну решает в том случае когда у тебя несколько методов в одном сервисе с одинаковыми кложурами

2023-01-13 11:17 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Services/SBPBankAppChecker/SBPBankAppChecker.swift
> +        guard let url = URL(string: "\(bank.schema)://") else { return }
очень хорошее замечание, поправил

2023-01-13 11:26 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPBanks/Presenter/SBPBanksPresenter.swift
> +        allBanksCellPresenters = [SBPBankCellNewPresenter](repeatElement(cellPresentersAssembly.build(cellType: .skeleton), count: 7))
сделал

2023-01-13 11:52 UTC, akhaman approved these changes

2023-01-13 12:00 UTC, merged