MIC 2707(part1)
Tinkoff/AcquiringSdk_IOS pull request #58
Opened 2021-04-09 14:31 UTC by grishamsc

2021-04-09 15:06 UTC, d-kv requested changes

2021-04-09 15:06 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUI/Cards/Implementations/DefaultCardsController.swift
> +        self.queue = queue
выглядит лишним

2021-04-09 15:06 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUITests/Cards/DefaultCardsControllerTests.swift
> +            cardsController.loadCards { result in
а почему нельзя этот вызов положить в completion для первого loadCards?

2021-04-09 15:29 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Cards/Implementations/DefaultCardsController.swift
> +        self.queue = queue
идея была в том, что бы внутри `DefaultCardsController` абстрагироваться от главной очереди, которая в данном случае выступает как очередь синхронизации. т.е. мы передаем просто какую-то очередь, она по-дефолту главная, но дальше с ней работа идет как с просто очередью. если вдруг это начнет аффектить главный поток - легко переключиться на другую серийную, просто передавая ее в инициализаторе

но, честно говоря, действительно есть ощущение, что может это некоторый перебор и проще просто синхронизироваться через главную очередь явно и все

2021-04-09 15:35 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUITests/Cards/DefaultCardsControllerTests.swift
> +            cardsController.loadCards { result in
я тут хочу проверить, что если вызвать `loadCards` и до того, как он отработает, вызвать `loadCards` еще раз, то первый вызов опустится и мы в completion обоих вызовов `loadCards` получим результат уже второго вызова

я у `mockCardsLoader` проставляю timeout 1 секунду
запускаю `loadCards`
затем через 0.5 секунды дергаю `loadCards` второй раз, ожидая, что первый вызов опустится, выполнится второй и `cardController` в `getCards()` будет отдавать результат, который был получен при втором вызове

2021-04-12 07:53 UTC, d-kv approved these changes

2021-06-09 09:10 UTC, elektroru approved these changes

2023-01-18 10:11 UTC, closed without merging