MIC 2707(part3) | CardsController - Adding card
Tinkoff/AcquiringSdk_IOS pull request #60
Opened 2021-04-09 14:34 UTC by grishamsc

2021-04-09 15:15 UTC, d-kv requested changes

2021-04-09 15:15 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +        modalViewController.cardsController = cardsAssembly.getCardsController(customerKey: customerKey)
тоже самое, зачем одному контроллеру знать про другой?

2021-04-09 15:15 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUI/Cards/Implementations/DefaultCardsController.swift
> +        if queue === DispatchQueue.main && Thread.isMainThread {
Здесь и правда нужно это переключение?

2021-04-09 15:39 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +        modalViewController.cardsController = cardsAssembly.getCardsController(customerKey: customerKey)
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/59#discussion_r610726163
:)

2021-04-10 19:35 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Cards/Implementations/DefaultCardsController.swift
> +        if queue === DispatchQueue.main && Thread.isMainThread {
в part 1 поменял логику синхронизации

2023-01-18 10:12 UTC, closed without merging